name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Perform a dry run"
        required: false
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build and publish mod
        run: |
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            export PUBLISH_DRY_RUN=1
          fi
          ./gradlew publishMod
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}